export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';