// Для ИНГРЕДИЕНТОВ
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';


// Для ДАННЫХ ИНГРЕДИЕНТА
export const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS';


// Для КОНСТРУКТОРА
export const ADD_INGREDIENT_CONSTRUCTOR = 'ADD_INGREDIENT_CONSTRUCTOR';
export const DELETE_INGREDIENT_CONSTRUCTOR = 'DELETE_INGREDIENT_CONSTRUCTOR';
export const CHANGE_INGREDIENTS_CONSTRUCTOR = 'CHANGE_INGREDIENTS_CONSTRUCTOR';


// Для ДАННЫХ ЗАКАЗА
export const GET_ORDER_DATA_REQUEST = 'GET_ORDER_DATA_REQUEST';
export const GET_ORDER_DATA_SUCCESS = 'GET_ORDER_DATA_SUCCESS';
export const GET_ORDER_DATA_FAILED = 'GET_ORDER_DATA_FAILED';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';

